apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "ecoscape-operator.labels" . | nindent 4 }}
  name: {{ include "ecoscape-operator.fullname" . }}-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ecoscape-operator.fullname" . }}-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: {{ include "ecoscape-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
