{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "ecoscape-operator.labels" . | nindent 4 }}
  name: {{ include "ecoscape-operator.serviceAccountName" . }}
{{- end }}
