# This rule is not used by the project ecoscape itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to experiment.cau-se.de resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ecoscape
    app.kubernetes.io/managed-by: kustomize
  name: experiment-viewer-role
rules:
- apiGroups:
  - experiment.cau-se.de
  resources:
  - experiments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - experiment.cau-se.de
  resources:
  - experiments/status
  verbs:
  - get
