apiVersion: ecoscape.cau-se.de/v1alpha1
kind: Experiment
metadata:
  labels:
    app.kubernetes.io/name: ecoscape
    app.kubernetes.io/managed-by: kustomize
  name: experiment-sample
spec:
  # TODO(user): Add fields here
