apiVersion: ecoscape.cau-se.de/v1alpha1
kind: Experiment
metadata:
  name: edge-sensor-pipeline-partition
  namespace: default
spec:
  topologyRef:
    name: two-zone-edge
  chaosPhaseRef:
    name: esp-stress-cloud

  duration:
    loadDelay: 30
    chaosDelay: 30
    topologyDelay: 15
    measurementDuration: 90
    repetitions: 2
    pauseBetweenRepetitions: 90

  manifests:
    sut:
      configMapRef:
        name: edge-sensor-pipeline-sut
    load:
      configMapRef:
        name: edge-sensor-pipeline-load
    monitor:
      configMapRef:
        name: edge-sensor-pipeline-monitor

  prometheus:
    url: "http://localhost:9090"
    queryTimeoutSeconds: 10

  slos:
    - name: stream-lag-berlin
      query: 'redis_stream_group_lag{zone="berlin"}'
      threshold: 50
      isBiggerBetter: false
      weight: 0.5

    - name: stream-lag-munich
      query: 'redis_stream_group_lag{zone="munich"}'
      threshold: 50
      isBiggerBetter: false
      weight: 0.5
