apiVersion: v2
name: ecoscape-operator
description: Helm chart for the Ecoscape Kubernetes operator
type: application
version: 0.2.0
appVersion: "0.2.0"
dependencies:
  - name: kube-prometheus-stack
    version: "91.5.2"
    repository: "https://prometheus-community.github.io/helm-charts"
    alias: prometheus
    condition: prometheus.enabled
  - name: chaos-mesh
    version: "2.8.4"
    repository: "https://charts.chaos-mesh.org"
    alias: chaosMesh
    condition: chaosMesh.enabled
  - name: strimzi-kafka-operator
    version: "1.2.0"
    repository: "https://strimzi.io/charts"
    alias: strimzi
    condition: strimzi.enabled
  - name: kafka-ui
    version: "1.6.5"
    repository: "https://ui.charts.kafbat.io/"
    alias: kafbat
    condition: kafbat.enabled
  - name: k6-operator
    version: "4.6.0"
    repository: "https://grafana.github.io/helm-charts"
    alias: k6operator
    condition: k6operatorEnabled
  - name: keda
    version: "2.21.0"
    repository: "https://kedacore.github.io/charts"
    alias: kedaOperator
    condition: kedaOperator.enabled
